import { jsPDF, GState } from 'jspdf';
import type { TailoredTipsResult } from './types';

export function generatePdfDocument(data: TailoredTipsResult) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const maxLineWidth = pageWidth - margin * 2;
  let y = 0;
  let pageNumber = 1;

  // -- Helpers --
  const setFont = (type: 'bold' | 'normal' | 'italic', size: number, color: [number, number, number]) => {
    doc.setFont('helvetica', type);
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
  };

  const addFooter = () => {
    doc.saveGraphicsState();
    setFont('normal', 9, [150, 150, 150]);
    doc.text(`Page ${pageNumber} | Generated by JD Analyzer`, pageWidth / 2, pageHeight - 30, { align: 'center' });
    doc.restoreGraphicsState();
  };

  const addWatermark = () => {
    doc.saveGraphicsState();
    doc.setGState(new GState({ opacity: 0.03 }));
    setFont('bold', 70, [0, 0, 0]);
    doc.text('JD ANALYZER', pageWidth / 2, pageHeight / 2, { angle: -45, align: 'center' });
    doc.restoreGraphicsState();
  };

  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - margin - 20) {
      addFooter();
      doc.addPage();
      pageNumber++;
      addWatermark();
      y = margin;
      return true;
    }
    return false;
  };

  // -- Page 1 Header --
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 120, 'F');
  
  setFont('bold', 28, [255, 255, 255]);
  doc.text('Tailored Resume Tips', margin, 70);
  
  setFont('normal', 11, [148, 163, 184]); // slate-400
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Generated on ${dateStr}`, margin, 95);

  y = 160;
  addWatermark();

  // -- Executive Summary --
  setFont('bold', 18, [15, 23, 42]);
  doc.text('Executive Summary', margin, y);
  
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(1);
  doc.line(margin, y + 8, pageWidth - margin, y + 8);
  y += 30;

  setFont('normal', 11, [51, 65, 85]); // slate-700
  const summaryLines = doc.splitTextToSize(data.executive_summary, maxLineWidth);
  checkPageBreak(summaryLines.length * 16 + 20);
  doc.text(summaryLines, margin, y, { lineHeightFactor: 1.5 });
  y += summaryLines.length * 16 + 40;

  // -- Bullet Point Rewrites --
  checkPageBreak(50);
  setFont('bold', 18, [15, 23, 42]);
  doc.text('Bullet Point Rewrites', margin, y);
  doc.line(margin, y + 8, pageWidth - margin, y + 8);
  y += 35;

  data.bullet_point_rewrites.forEach((bullet) => {
    const parts = bullet.split('->');
    let original = bullet;
    let rewrite = '';
    
    if (parts.length > 1) {
      original = parts[0].trim();
      rewrite = parts.slice(1).join('->').trim();
    }

    // Original Block
    checkPageBreak(60);
    doc.setFillColor(254, 242, 242); // red-50
    doc.rect(margin, y, maxLineWidth, 18, 'F');
    setFont('bold', 9, [220, 38, 38]); // red-600
    doc.text('CURRENT BULLET', margin + 8, y + 12);
    y += 30;

    setFont('normal', 10, [71, 85, 105]); // slate-600
    const origLines = doc.splitTextToSize(original, maxLineWidth - 10);
    checkPageBreak(origLines.length * 14 + 20);
    doc.text(origLines, margin + 5, y, { lineHeightFactor: 1.4 });
    y += origLines.length * 14 + 15;

    // Suggested Block
    if (rewrite) {
      checkPageBreak(60);
      doc.setFillColor(240, 253, 244); // green-50
      doc.rect(margin, y, maxLineWidth, 18, 'F');
      setFont('bold', 9, [22, 163, 74]); // green-600
      doc.text('SUGGESTED REVISION', margin + 8, y + 12);
      y += 30;

      setFont('normal', 10, [15, 23, 42]); // dark
      const newLines = doc.splitTextToSize(rewrite, maxLineWidth - 10);
      checkPageBreak(newLines.length * 14 + 15);
      doc.text(newLines, margin + 5, y, { lineHeightFactor: 1.4 });
      y += newLines.length * 14 + 35;
    } else {
      y += 20;
    }
  });

  // -- Interview Prep Focus --
  checkPageBreak(50);
  setFont('bold', 18, [15, 23, 42]);
  doc.text('Interview Prep Focus', margin, y);
  doc.line(margin, y + 8, pageWidth - margin, y + 8);
  y += 35;

  data.interview_prep_focus.forEach((focus, i) => {
    setFont('bold', 11, [15, 23, 42]);
    checkPageBreak(25);
    doc.text(`Point ${i + 1}`, margin, y);
    y += 18;

    setFont('normal', 11, [51, 65, 85]);
    const lines = doc.splitTextToSize(focus, maxLineWidth - 15);
    checkPageBreak(lines.length * 16 + 15);
    
    // Draw a small bullet
    doc.setFillColor(15, 23, 42);
    doc.circle(margin + 4, y - 4, 2, 'F');

    doc.text(lines, margin + 15, y, { lineHeightFactor: 1.5 });
    y += lines.length * 16 + 20;
  });

  // Add footer to the last page
  addFooter();

  // Trigger download
  doc.save('JD-Analyzer-Tailored-Tips.pdf');
}
